#! /bin/bash

# 构建容器
docker build -t mcp-client-dingtalk .

# 启动容器
docker run -d --name mcp-client-dingtalk \
-e RDB_HOST=${RDB_HOST} \
-e RDB_PORT=${RDB_PORT} \
-e RDB_USER=${RDB_USER} \
-e RDB_PASSWORD=${RDB_PASSWORD} \
-e RDB_DATABASE=${RDB_DATABASE} \
-e DINGTALK_CLIENT_ID=${DINGTALK_CLIENT_ID} \
-e DINGTALK_CLIENT_SECRET=${DINGTALK_CLIENT_SECRET} \
-e DINGTALK_CARD_TEMPLATE_ID_USER_CONFIG=${DINGTALK_CARD_TEMPLATE_ID_USER_CONFIG} \
-e DINGTALK_CARD_TEMPLATE_ID_CALL_TOOLS=${DINGTALK_CARD_TEMPLATE_ID_CALL_TOOLS} \
-e MCP_SERVER_0_NAME=${MCP_SERVER_0_NAME} \
-e MCP_SERVER_0_URL=${MCP_SERVER_0_URL} \
mcp-client-dingtalk

